services:
  - type: web
    name: clicker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: "postgresql://chak_db_user:6RA10RM6B89kVQgBVrRQ1jZ0DUWfOwLS@dpg-csiandbgbbvc73fi51og-a.oregon-postgres.render.com:5432/chak_db"